### ISSUE TITLE
Database tables not installing

### ISSUE THREAD

**Issue by dshastry** [decadeofdefeat/livestagram#1]
The database tables are not installing when using the "/livestagram/install" URL. Tables had to be manually installed by copying SQL code from install_model to PHPmyadmin

**Comment by decadeofdefeat** [comment]
This is resolved now with my latest update. I never added the .htaccess file required for mod-rewrite.

**Comment by lincolnlemos** [comment]
I still got the same problem. I installed tables manually, but the admin is not working. Check it. I got 404 error to all pages. http://momentoinprint.com/app/admin/login

**Comment by decadeofdefeat** [comment]
Have you checked that your .htaccess file is uploaded, and that your web server is Apache and is properly configured to accept .htaccess redirects?

**Comment by lincolnlemos** [comment]
Yes.. I run a wp with permalinks in same server...

**Comment by decadeofdefeat** [comment]
Okay, I'm not sure how I can help you. Perhaps look on Code Igniter's website for troubleshooting .htaccess? I'm pretty sure your issue has nothing to do with my code.
